### ISSUE TITLE
Tag Lost exception for Yubikey NEO

### ISSUE THREAD

**Issue by innovate-invent** [brush701/yubichallenge#3]
Yubikey NEO takes slightly longer than the default timeout to generate a response given some challenges.
You need to set a longer timeout with: https://developer.android.com/reference/android/nfc/tech/IsoDep.html#setTimeout(int)

https://github.com/brush701/yubichallenge/blob/ef698dc169d6b3a9999915fdd424f13c9e142121/app/src/main/java/com/yubichallenge/NFCActivity.java#L98

**Comment by lloyda** [comment]
I've taken a branch and can confirm that adding a Timeout call resolved my issue with this app.

**Comment by innovate-invent** [comment]
@lloyda Could you submit a PR?

**Comment by lloyda** [comment]
@innovate-invent created the PR.  New to this git game, so hopefully got it right!

Presumably though it will require @brush701 to create a new app in the store?  I'm running a locally installed apk, so not a problem for me.

**Comment by innovate-invent** [comment]
Issue resolved by #4
